# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    container_name: refactoringme_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - refactoringme_mariadb_data:/var/lib/mysql

volumes:
  refactoringme_mariadb_data: